---
- name: ensure systemd dozzle.service
  notify: restart service dozzle
  ansible.builtin.copy:
    dest: /etc/systemd/system/dozzle.service
    owner: root
    group: root
    mode: "0644"
    content: |
      [Unit]
      Requires=docker.service
      After=docker.service
      StartLimitIntervalSec=0
      [Service]
      ExecStartPre=-/usr/bin/docker rm --force %N
      ExecStart=/usr/bin/docker run \
        --name=%N \
        --rm=true \
        --pid=host \
        --stop-timeout=30 \
        --network={{ dozzle_docker_network }} \
        {% if dozzle_docker_network != 'host' %}{% for publish in dozzle_docker_publish_ports -%}
        --publish={{ publish }} \
        {% endfor %}{% endif -%}
        --volume=/var/run/docker.sock:/var/run/docker.sock:rw \
        {% if dozzle_docker_labels | length > 0 %}{% for key, value in dozzle_docker_labels.items() -%}
        --label={{ key }}="{{ value }}" \
        {% endfor %}{% endif -%}
        {{ dozzle_docker_image }} --no-analytics=true
          {{- ' --level='~dozzle_log_level if dozzle_log_level }}
          {{- ' --base='~dozzle_basepath if dozzle_basepath }}
          {{- ' --username='~dozzle_username if dozzle_username }}
          {{- ' --password='~dozzle_password if dozzle_password }}
          {{- ' --filter='~dozzle_filter | join(' --filter=') if dozzle_filter }}
      ExecStop=/usr/bin/docker stop %N
      Restart=always
      RestartSec=10
      KillMode=process
      [Install]
      WantedBy=multi-user.target

- name: execute handlers
  ansible.builtin.meta: flush_handlers

- name: start service dozzle
  ansible.builtin.systemd:
    name: dozzle
    daemon_reload: true
    enabled: true
    state: started
